spring.application.name=backend

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_advisor_db
spring.datasource.username=postgres
spring.datasource.password=dikshita
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=8080

# AI Service
ai.service.url=http://localhost:8000